// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdZ23PE0_2k96WcEVjvjFrjhzoEaHwrKI',
    appId: '1:143986214921:web:a72acdb6b46b37cd89d0d8',
    messagingSenderId: '143986214921',
    projectId: 'demo1-de9e9',
    authDomain: 'demo1-de9e9.firebaseapp.com',
    storageBucket: 'demo1-de9e9.firebasestorage.app',
    measurementId: 'G-PNMJV9ZEG7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs0QEo4fOql-trChqS183MoTpMegsPPt8',
    appId: '1:143986214921:android:f2fef41291858c7889d0d8',
    messagingSenderId: '143986214921',
    projectId: 'demo1-de9e9',
    storageBucket: 'demo1-de9e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCwQ2UOUUNXid4EQ9XAN8zpGv9-qxZmMY',
    appId: '1:143986214921:ios:481acbdc9b5f07ba89d0d8',
    messagingSenderId: '143986214921',
    projectId: 'demo1-de9e9',
    storageBucket: 'demo1-de9e9.firebasestorage.app',
    iosBundleId: 'com.example.firebasetestproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCwQ2UOUUNXid4EQ9XAN8zpGv9-qxZmMY',
    appId: '1:143986214921:ios:481acbdc9b5f07ba89d0d8',
    messagingSenderId: '143986214921',
    projectId: 'demo1-de9e9',
    storageBucket: 'demo1-de9e9.firebasestorage.app',
    iosBundleId: 'com.example.firebasetestproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdZ23PE0_2k96WcEVjvjFrjhzoEaHwrKI',
    appId: '1:143986214921:web:c8b8d358e86d586389d0d8',
    messagingSenderId: '143986214921',
    projectId: 'demo1-de9e9',
    authDomain: 'demo1-de9e9.firebaseapp.com',
    storageBucket: 'demo1-de9e9.firebasestorage.app',
    measurementId: 'G-HKEWQKRWW5',
  );
}
